name: main

on:
  push:
    branches:
      - master
  pull_request:

env:
  PYTEST_ADDOPTS: "-m 'not (edge or safari)'"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: python 3.6
            python: 3.6
            tox_env: py36
            os: ubuntu-latest

          - name: python 3.7
            python: 3.7
            tox_env: py37
            os: ubuntu-latest

          - name: python 3.8
            python: 3.8
            tox_env: py38
            os: ubuntu-latest

          - name: python 3.9
            python: 3.9
            tox_env: py39
            os: ubuntu-latest

          - name: pypy 3.7
            python: pypy-3.7
            tox_env: pypy37
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Setup Firefox
      uses: browser-actions/setup-firefox@latest
      with:
        firefox-version: latest

    - name: Setup Geckodriver
      uses: browser-actions/setup-geckodriver@latest

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@master

    - name: Run tests
      run: "tox -e ${{ matrix.tox_env }}"

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests
      run: "tox -e docs"

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests
        run: "tox -e linting"
