name: test

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:
  workflow_call:

env:
  PYTEST_ADDOPTS: "-m 'not (edge or safari)'"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy-3.8"]
        os: [ubuntu-latest, windows-latest]
        include:
          - python: "3.6"
            tox_env: "py36"
          - python: "3.7"
            tox_env: "py37"
          - python: "3.8"
            tox_env: "py38"
          - python: "3.9"
            tox_env: "py39"
          - python: "3.10"
            tox_env: "py310"
          - python: "pypy-3.8"
            tox_env: "pypy3"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Setup Firefox
      if: matrix.os == 'ubuntu-latest'
      uses: browser-actions/setup-firefox@latest
      with:
        firefox-version: latest

    - name: Setup Geckodriver
      if: matrix.os == 'ubuntu-latest'
      uses: browser-actions/setup-geckodriver@latest

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@master

    - name: Cache tox environments
      uses: actions/cache@v3
      with:
        path: .tox
        key: tox-${{ matrix.os }}-${{ matrix.python }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

    - name: Test
      if: matrix.os == 'ubuntu-latest'
      run: tox -e ${{ matrix.tox_env }}

    - name: Test (skip firefox on windows)
      if: matrix.os == 'windows-latest'
      env:
        PYTEST_ADDOPTS: "-m 'not (edge or safari or firefox)'"
      run: tox -e ${{ matrix.tox_env }}

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests
      run: "tox -e docs"
